Hebrew support
nielsfaber/scheduler-card pull request #347
Opened 2021-03-14 09:23 UTC by yaccri

2021-03-14 10:24 UTC, nielsfaber requested changes

2021-03-14 10:24 UTC, nielsfaber commented on src/localize/languages/he.json
> +        "no_entities_for_group": אין יישויות בקבוצה זו",
Missing a bracket here

2021-03-14 10:24 UTC, nielsfaber commented on src/localize/languages/he.json
> +© 2021 GitHub, Inc.
All below closing bracket should be removed.

2021-03-22 16:21 UTC, nielsfaber commented
@yaccri  can you update this pull request with the changes I've commented?

2021-03-22 18:51 UTC, yaccri commented on src/localize/languages/he.json
> +        "no_entities_for_group": אין יישויות בקבוצה זו",
"no_entities_for_group": "אין יישויות בקבוצה זו",

2021-03-22 18:51 UTC, yaccri commented on src/localize/languages/he.json
> +        "no_entities_for_group": אין יישויות בקבוצה זו",
```suggestion
        "no_entities_for_group": "אין יישויות בקבוצה זו",

```

2021-03-22 18:54 UTC, yaccri commented
I'm not sure if it's corrected as I intended.
Line 110 had a missing quote and should be:         "no_entities_for_group": אין יישויות בקבוצה זו",

2021-03-22 19:51 UTC, nielsfaber commented
Good enough for me 👍 
Thanks again!

2021-03-22 19:51 UTC, merged